### ISSUE TITLE
Extension still works after uninstalling

### ISSUE THREAD

**Issue by juliusav** [muaz-khan/Firefox-Extensions#5]
The extension works great, but when I uninstall via Firefox Add-ons Manager, the mozGetUserMedia() call still works and continues to ask for which window to share. I'm currently using mozGetUserMedia() to check if the user has the extension properly installed, so this raises some issues for me.

I see the following in the source code:
`unload(function() {
    // remove only my own domains
    removeMyDomainOnUnInstall();
});`

It looks like the extension shouldn't work after this... could it be that the unload function isn't working properly?

Thanks

**Comment by carloscarcamo** [comment]
same problem here!

**Comment by juliusav** [comment]
@carloscarcamo I just found the source of the issue and committed a fix for it: https://github.com/muaz-khan/Firefox-Extensions/pull/6
